### ISSUE TITLE
Back Button Issue in Conversation view controller

### ISSUE THREAD

**Issue by saadabouelsooud** [Jungle-Works/Hippo-iOS-SDK#3]
Back Button didn't show completely in conversation view controller when the keyboard would be activated. 
![WhatsApp Image 2019-04-17 at 1 58 40 PM](https://user-images.githubusercontent.com/8465396/56286656-8f232580-611a-11e9-813b-020a7e66074f.jpeg)
![WhatsApp Image 2019-04-17 at 1 58 48 PM](https://user-images.githubusercontent.com/8465396/56286657-8fbbbc00-611a-11e9-92dc-ba1034ff11d6.jpeg)

**Comment by vishaljhanjhri** [comment]
Hi @saadabouelsooud ,

Can you tell the Hippo Version?
