### ISSUE TITLE
Issues integrating Hippo SDK

### ISSUE THREAD

**Issue by ZNickq** [Jungle-Works/Hippo-iOS-SDK#4]
Hi,

While attempting to implement this sdk as an update to the old Fugu SDK I've run into 2 issues:

1. https://api.hippochat.io/ seems to have an invalid SSL certificate: all requests fail with errors that look like this:
`2020-02-25 17:58:28.253399+0200 App[21633:4365073] Task <A2A24D24-164A-4F20-A2A3-8F03D5209510>.<1> finished with error [-1202] Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “api.hippochat.io” which could put your confidential information at risk." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x2827d83f0>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, NSErrorPeerCertificateChainKey=(
    "<cert(0x109012000) s: *.fuguchat.com i: COMODO RSA Domain Validation Secure Server CA>",
    "<cert(0x109012c00) s: COMODO RSA Domain Validation Secure Server CA i: COMODO RSA Certification Authority>",
    "<cert(0x109013600) s: COMODO RSA Certification Authority i: AddTrust External CA Root>"
), NSUnderlyingError=0x281bb7960 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x2827d83f0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x109012000) s: *.fuguchat.com i: COMODO RSA Domain Validation Secure Server CA>",
    "<cert(0x109012c00) s: COMODO RSA Domain Validation Secure Server CA i: COMODO RSA Certification Authority>",
    "<cert(0x109013600) s: COMODO RSA Certification Authority i: AddTrust External CA Root>"
)}}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “api.hippochat.io” which could put your confidential information at risk., NSErrorFailingURLKey=https://api.hippochat.io/api/users/putUserDetails, NSErrorFailingURLStringKey=https://api.hippochat.io/api/users/putUserDetails, NSErrorClientCertificateStateKey=0}`

I managed to fix this by changing the Hippo HTTPClient to accept any SSL connection, however now I am running into a second issue: the library crashes internally because  'https://api.hippochat.io/api/users/putUserDetails' returns a 404.

I've attached an image of a postman request failing so you can see what i'm talking about.

<img width="743" alt="Screenshot 2020-02-25 at 18 00 58" src="https://user-images.githubusercontent.com/980516/75264909-cbbeb380-57f8-11ea-99cd-c37e08acffb0.png">

Any help on fixing these issues would be appreciated!

**Comment by gianios** [comment]
@ZNickq Please update your Hippo-iOS-SDK with version 2.1.7 and then let me know issue resolved or not?
