### ISSUE TITLE
Compile fail with chip M1

### ISSUE THREAD

**Issue by moonjava2005** [Jungle-Works/Hippo-iOS-SDK#7]
We're using Apple chip M1 and got this compile error
`<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios10.0'
/......../ios/Pods/Hippo/Hippo/Controllers/Payment/RazorPayViewController.swift:9:8: error: module compiled with Swift 5.5.1 cannot be imported by the Swift 5.6 compiler: /...../ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule
import Razorpay`

**Comment by rahulvermaJW** [comment]
Use open using rosetta mode feature
